Create 06-22-2017-Sandhya-Subramanian.md
CSWomenUMass/cswomenumass.github.io pull request #81
Opened 2017-07-12 14:44 UTC by nidhimundra

@etosch: Please have a look.

2017-07-12 15:57 UTC, etosch requested changes
Looks like a great start. Here just some quick updates I'd suggest:

(1) Blog posts need to start with metadata, otherwise they won't show up. Here's the metadata from the last blog post: 

````
layout: post
title: "Amanda Doucette Travels to the Cognitive Modeling and Computational Linguistics workshop at EACL 2017"
date: 2017-04-20 00:00:00
categories: travelgrant
author: sofya
````

(a) If you don't include the date or title, jekyll will infer them from the file name. I suggest making a slighly more descriptive title, like "Sandhya Subramanian presents ICAPS paper thanks to CS Women Travel Grant" or something like that. 

(b) You'll need to add yourself to as an author to the [config](../blob/master/_config.yml) file for your name to show up as an author (I strongly recommend doing this -- it helps to show the breadth of women who have contributed to the blog)

(2) Ping Sandhya about a photo from the conference. This kind of thing really helps sell the post and make the website look nice. Good publicity helps CS Women win awards like the Women for UMass award. When I haven't been able to get a photo, I've searched [openclipart.org](http://openclipart.org) for something. 

(3) I recommend writing an intro blurb reminding readers of what the travel grant is. Some of the [Grace](../blob/master/_posts/2015-10-27-grace-hopper-2015-part-1.md) [Hopper](../blob/master/_posts/2015-11-08-grace-hopper-2015-part-2.md) posts are good examples.

2017-07-25 01:35 UTC, nidhimundra commented
@etosch: Made the suggested changes. Have a look and let me know if something needs to be changed further.

2017-07-25 13:27 UTC, etosch approved these changes

2017-07-25 13:27 UTC, merged

2017-07-25 13:30 UTC, etosch commented
The page displays properly locally, so I approved the pull request. However, you might want to add the thumbnail option to the metadata, e.g.

`thumbnail: images/travelgrant/panel_ICAPS.jpg`